[workspace]
resolver = "2"
package.edition = "2021"

members = ["rust/sqlite_red", "rust/sqlite_yellow"]


[workspace.dependencies]
sqlx = { version = "0.8", features = ["runtime-tokio"] }
tokio = { version = "1.44.2", features = ["full"] }
anyhow = { version = "1" }
